name: shrub
version: 0.0.0
description: Compiler, analyzer, and toolchain for the Shrub language.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/shrub-lang/shrub
executables:
  shrub: shrub
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  args: ^1.0.0
  build: ^1.0.0
  dart_language_server: ^0.1.14
  source_span: ^1.0.0
  string_scanner: ^1.0.0
dev_dependencies:
  build_runner: ^1.0.0
  pedantic: ^1.0.0
  test: ^1.0.0