name: shrub_cli
dependencies:
  angel_framework: ^1.1.0
  angel_static: ^1.3.0
  args: ^1.0.0
  file: ^2.0.0
  html: ^0.13.0
  io: ^0.3.2
  path: ^1.0.0
  watcher: ^0.9.7
  shrub:
    path: ../shrub
executables:
  shrub: shrub